### ISSUE TITLE
Disable Debug 

### ISSUE THREAD

**Issue by suryanarayanms** [Rapid-Technology/flutter_splash_screen#1]
Unable to disable debug tag using debugShowCheckedModeBanner: false, in materialapp

**Comment by yasin1376** [comment]
Can you run this command (flutter doctor) and show us your code?

**Comment by suryanarayanms** [comment]
> Can you run this command (flutter doctor) and show us your code?

Thanks. 
Got the solution. 
It was actually my mistake. 
Mistake: I didn't add "debugShowCheckedModeBanner" in Materialapp. I was adding in my statefulwidget class.
